version: 2

jobs:

  py362:
    working_directory: ~/py362_matscholar_web
    docker:
      - image: circleci/python:3.6.2
        environment:
          SKIP_INTENSIVE: 1
    steps:
      - checkout

    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: setup env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install -q --upgrade pip

            pip install --quiet -e . -r requirements.txt
            python setup.py test
          no_output_timeout: 10m

      - save_cache:
          paths:
          - ./test_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}


  code_style:
    working_directory: ~/py362_matscholar_web
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements_dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: setup env and run code check
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --quiet -r requirements_dev.txt
          no_output_timeout: 10m

      - save_cache:
          paths:
            - ./test_env
          key: v1-dependencies-{{ checksum "requirements_dev.txt" }}



workflows:
  version: 2
  run_tests_on_commit:
    jobs:
      - py362
      - code_style